export enum Rol {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  PERSONAL_ADMINISTRATIVO = 'PERSONAL_ADMINISTRATIVO',
  INTEGRANTE = 'INTEGRANTE',
}

export const ADMIN_WRITE_ROLES = [
  Rol.PERSONAL_ADMINISTRATIVO,
  Rol.ADMIN,
  Rol.SUPER_ADMIN,
] as const;

export const ADMIN_DELETE_ROLES = [Rol.ADMIN, Rol.SUPER_ADMIN] as const;
