/**
 * Side-effect CSS imports from `node_modules`.
 *
 * Leaflet ships its stylesheet as a file you import for its effect, not for
 * a value. Next's bundler handles that fine, but TypeScript has no idea what
 * a `.css` module is and fails the build with TS2307 — so the shape is
 * declared here once.
 *
 * `next-env.d.ts` covers CSS Modules (`*.module.css`) only, and it is
 * regenerated by Next on every build, so it is not a place to add anything.
 */
declare module '*.css';
